apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - namespace.yaml
  - network-policy.yaml
  - prowlarr/
  - sonarr/
  - radarr/
  - lidarr/
  - readarr/
  - bazarr/
  - sabnzbd/
  - plex/
  - overseerr/
  - tautulli/
  - recyclarr/
