apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library
  namespace: media
spec:
  accessModes:
    - ReadWriteMany # Requires NFS, Longhorn type RWX, or hostPath on single node
  storageClassName: capacity-storage # RAID Tier
  resources:
    requests:
      storage: 10Ti
